# Generated by Django 5.1.6 on 2025-02-27 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.module'),
        ),
        migrations.AlterField(
            model_name='profnotification',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
