# Generated by Django 5.1.6 on 2025-02-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profnotification',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_notifications', to='api.projet'),
        ),
    ]
