# Generated by Django 5.1.6 on 2025-02-27 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profnotification_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profnotification',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_prof', to='api.projet'),
        ),
    ]
