# Generated by Django 5.1.6 on 2025-02-27 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profnotification_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspaceCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membres', models.ManyToManyField(related_name='collaborations', to=settings.AUTH_USER_MODEL)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='espace_collaboration', to='api.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='messages_fichiers/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='messages_audios/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.espacecollaboration')),
            ],
        ),
    ]
